# Generated by Django 3.0 on 2020-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome', models.CharField(max_length=255)),
                ('assembly', models.CharField(max_length=255)),
                ('track', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'source',
            },
        ),
    ]
